* Temporary parameter list file for ITRS 2011 ver2 models
.lib 20nm
.param vdd=0.9
.param vddp=-0.9
.param fin_height=28n
.param fin_width=15n
.param lg=24n
.endl

.lib 16nm
.param vdd=0.85
.param vddp=-0.85
.param fin_height=26n
.param fin_width=12n
.param lg=20n
.endl

.lib 14nm
.param vdd=0.8
.param vddp=-0.8
.param fin_height=23n
.param fin_width=10n
.param lg=18n
.endl

.lib 10nm
.param vdd=0.75
.param vddp=-0.75
.param fin_height=21n
.param fin_width=9n
.param lg=14n
.endl

.lib 7nm
.param vdd=0.7
.param vddp=-0.7
.param fin_height=18n
.param fin_width=7n
.param lg=11n
.endl

