.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH CMPP 1 "2014-10-28"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
cmpp \- Code Model PreProcessor
.SH SYNOPSIS
.B cmpp
.RI \-ifs
.br
.B cmpp
.RI \-mod
.RI [<filename>]
.br
.B cmpp
.RI \-lst
.br
.SH DESCRIPTION
This manual page documents briefly the
.B cmpp
command.

.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics,
.\" respectively.
\fBcmpp\fP is a is a code model preprocessor for the XSpice program.
.SH OPTIONS
All options for this program start with one dash (`-').
A summary of options is included below.
.TP
.B \-ifs
Process Interface Specification File
.TP
.B \-mod [<filename>]
Process Model Definition File (default filename cfunc.mod)
.TP
.B \-lst
Process Pathname List Files
.br
.SH AUTHOR
cmpp was written by Bill Kuhn and Steve Tynor.
.PP
This manual page was written by Gudjon I. Gudjonsson <gudjon@gudjon.org>,
for the Debian project (and may be used by others).
