.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH NGPROC2MOD 1 "2012-06-04"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
ngprog2mod \- program to process BSIM1 and BSIM2 files.
.SH SYNOPSIS
.B ngprog2mod
.SH DESCRIPTION
This manual page documents briefly the
.B ngprog2mod
command.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics,
.\" respectively.
\fBngprog2mod\fP is a program that changes a BSIM1 or BSIM2 process file to an
ngspice model file.
.SH OPTIONS
The program doesn't support any command lines arguments. Just run the program
and it will ask for input.
.br
.SH AUTHOR
ngprog2mod was written at the University of California.
.PP
This manual page was written by Gudjon I. Gudjonsson <gudjon@gudjon.org>,
for the Debian project (and may be used by others).
